### ISSUE TITLE
Backface culling not working properly.

### ISSUE THREAD

**Issue by SkybuckFlying** [martynafford/natural-earth-geojson#1]
I am trying to render polygon lines in such a way that only the front of the sphere/globe is showing, but some parts of the backside is also showing, I am not sure why this is, perhaps an issue with the input data ? or perhaps the conversion process ? or perhaps some issue with GLScene or OpenGL ?

https://youtu.be/stQoXVrZgtA

Correct video link will be:

https://youtu.be/dEiZ3wIyaLw

if google manages to process it.

I had to cut something off at the end, some sensitive data was leaked :)

**Comment by martynafford** [comment]
Greetings.

The data here are direct conversions of the data from [Natural Earth](http://www.naturalearthdata.com/) using [ogr2ogr](http://www.gdal.org/ogr2ogr.html). If there are any issues, you'd be best taking it up with them.

Good luck in your endeavors.
