### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by mfranke93** [martynafford/natural-earth-geojson#2]
First of all, thank you for creating this! I have used the GeoJSON data from here regularly, as I'm sure many others have as well.

However, because you have not added a license to the repository, the default copyright laws apply (see second paragraph [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license)). The source data from NaturalEarth is in the public domain, but your derivative work is not[^1]. Maybe that was your intention, but I would guess not. In any case, the usefulness of the repository to others is diminished because technically, no one may re-use this work in any published other work. 

If that was not your intention, please add a suitable LICENSE file. [choosealicense.com](https://choosealicense.com/non-software/) has some suggestions for non-software repositories. Might I suggest [CC0-1.0](https://choosealicense.com/licenses/cc0-1.0/) (the public domain license), or [CC-BY-4.0](https://choosealicense.com/licenses/cc-by-4.0/)? If you would like, I can also submit a PR with the license, which you just have to approve.

[^1]: At the very least, the copyright situation is unclear and up to interpretation, depending on how [substantial your own transformations are](https://en.wikipedia.org/wiki/Derivative_work).

**Comment by martynafford** [comment]
Thank you for your feedback.

While there's nothing in this repository, short of the script, that could be called my own work, an explicit licence may save others some headache.

I have added the CC0 licence.

All the best.
